# Generated by Django 5.2.7 on 2026-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_invite_code_total_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
